### ISSUE TITLE
Lambda Data source failed with the following error {}

### ISSUE THREAD

**Issue by chaitanya11** [bboure/serverless-appsync-simulator#27] opened 2020-05-18 14:42 UTC
**Describe the bug**
Unable to get error message from resolvers in pipeline
`Lambda Data source failed with the following error
{}
`

**To Reproduce**
create a pipeline functions, throw exception in first function of the pipeline, try to catch error message in VTL template or the response from appsync

**Expected behavior**
Should be able to capture error message in VTL

**Screenshots**
<img width="1085" alt="Screenshot 2020-05-18 at 8 10 31 PM" src="https://user-images.githubusercontent.com/16046840/82226098-afd43500-9943-11ea-87e7-7df69c612d4b.png">

**Additional context**
Getting empty error object in Lambda dataloader exception block

**Comment by bboure** [comment] 2020-05-18 14:52
@chaitanya11 Thank you for logging this issue.

> create a pipeline functions, throw exception in first function of the pipeline, try to catch error message in VTL template or the response from appsync

Could you show us how you try to catch the error in VTL?

**Comment by chaitanya11** [comment] 2020-05-18 15:17
sure @bboure 

here is my response mapping template for the first function in pipeline 

```
#if( $context.result && $context.result.errorMessage )
    $util.error($context.result.errorMessage, $context.result.errorType, $context.result.stack)
#elseif( $context.result && $context.result.errors )
	$util.error($context.result.error, 'Error', $context.result.errors)
#else
    $util.toJson($context.result)
#end

```

here is my request mapping template for the second function in pipeline.
```
#if( $context.result && $context.result.errorMessage )
    $util.error($context.result.errorMessage, $context.result.errorType, $context.result.stack)
#elseif( $context.result && $context.result.errors )
	$util.error($context.result.error, 'Error', $context.result.errors)
#end
{
    "payload": { "query": $utils.toJson($context.prev.result) }
}

```

**Comment by bboure** [comment] 2020-05-18 20:18
@chaitanya11  the error you see in the logs is just for debugging purpose. 

According to the doc, it is up to you to handle the errors in the response template.

Looking at your response template I think there is either a typo, or you are missing an `if`

Try adding:

```vtl
#elseif($context.error)
  $util.error($context.error.message)
```

**Comment by chaitanya11** [comment] 2020-05-19 05:07
@bboure since the error object is empty this condition will not occur, and program will try to convert the empty object to json which will cause `unable to convert to <template> to class com.amazonaws.deepdish.transform.model.lambda.LambdaVersionedConfig` error.

**Comment by bboure** [comment] 2020-05-19 05:25
@chaitanya11 ok I understand. Looks like the Error thrown is Empty.

Now that I think about it, I have noticed this issue too in the past. 
I think the issue is [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts#L40) (and [here](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-util-mock/src/utils/lambda/execute.ts#L38) for the current version of the package)

`_.assign` gets rid of the `message` part of the `Error` object.

I discussed it recently in [this comment](https://github.com/aws-amplify/amplify-cli/pull/4203/files#r422466105), but I did not think of this use-case you are having. 

I will try to confirm this is the issue and fix it.

thank you for the details!

**Comment by chaitanya11** [comment] 2020-05-19 11:50
@bboure  this scenario is working fine in aws with template version `2018-05-29` but not in simulator. With `2017-02-28` version we are facing problems in both aws and in simulator.

**Comment by bboure** [comment] 2020-06-05 10:51
There is an open PR that fixe this issue:
https://github.com/aws-amplify/amplify-cli/pull/4418

**Comment by chaitanya11** [comment] 2020-06-09 03:38
thank you for your efforts @bboure 👍

**Comment by bboure** [comment] 2020-07-27 09:53
Fixed with https://github.com/aws-amplify/amplify-cli/pull/4418

**Closed by bboure** 2020-07-27 09:53 UTC
