### ISSUE TITLE
Big responses seem to "get lost" - they time out

### ISSUE THREAD

**Issue by FilipPyrek** [bboure/serverless-appsync-simulator#32] opened 2020-06-02 12:56 UTC
**Describe the bug**
When I return a big long array, the response seems to be loading indefinitely and then it times-out.

I did some digging and I discovered that the issue comes from here:
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts#L94

According to [this discussion](https://github.com/nodejs/help/issues/1265#issuecomment-388365110) the limit for `process.send` payload seems to be `65536`. And when I tested it, it really stopped working after crossing this boundary. Unfortunately it doesn't throw any error.

**To Reproduce**
Return some big long array as response.

**Expected behavior**
Whole array should be returned in the response. There should be no timeouts.

**Comment by FilipPyrek** [comment] 2020-06-02 12:57
I'm going to submit an issue to [aws-amplify/amplify-cli](https://github.com/aws-amplify/amplify-cli)

**Comment by FilipPyrek** [comment] 2020-06-02 13:12
The issue: https://github.com/aws-amplify/amplify-cli/issues/4439

**Comment by bboure** [comment] 2020-06-04 16:08
Thanks. Let's see if they giv esome feedback on the issue

Quick question. Is your array that big because it has few large items or lots of small items??

Regardless of the issue, 65K+ seems like a pretty huge response.
Can't you (or, dare I say, shouldn't you) use pagination?

**Comment by FilipPyrek** [comment] 2020-06-04 19:50
> Is your array that big because it has few large items or lots of small items??

Big because it has few large items.

> Can't you (or, dare I say, shouldn't you) use pagination?

Yes, you might be right - but this plugin is called `serverless-appsync-simulator` and it should simulate as much as possible the AWS environment. And in this case - it didn't work locally, but it worked deployed on AWS.
I think that limit on AWS is around [6 Megabytes](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html).

Also for example if you use `BatchInvoke`, then this 65K limitation is even more frustrating...

**Comment by bboure** [comment] 2020-06-04 20:20
Good point @FilipPyrek 
Let's see what they say

**Comment by moelholm** [comment] 2020-06-20 19:44
I've hit this limitation too. I created a sample project that illustrates the issue:

https://github.com/moelholm/appsync-simulator-responsesize-bug/blob/master/src/greetings.ts

... just a lot of data - and the request hangs. @FilipPyrek I'm quite sure you got it right: the issue is in code originating from the amplify project. Maybe we should fix it for them 😅

**Comment by FilipPyrek** [comment] 2020-06-20 21:14
Hi @moelholm, thanks for the sample, let's push them in the discussion under the issue! 😀  https://github.com/aws-amplify/amplify-cli/issues/4439
It already has got some labels added and it got an assignee. So hopefully it will get fixed soon.

**Comment by bboure** [comment] 2020-06-21 12:00
I started experiencing issues with big responses too recently. 
I did not double check but I am pretty sure this is the same issue. 
Let's hope they give some feedback soon

**Comment by bboure** [comment] 2020-07-27 09:44
Good news. https://github.com/aws-amplify/amplify-cli/pull/4906 fixed the issue. It has already been released. 
It came with a small recession issue which [I have fixed](https://github.com/aws-amplify/amplify-cli/pull/4941). Hope this gets merged soon.

I also got https://github.com/aws-amplify/amplify-cli/pull/4421 merged but it has not been released yet. Once it is, I'll get rid of [this hack](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/data-loaders/LambdaDataLoader.js)

After that, I'll create a new version of the plugin which includes all the improvements. Hopefully, very soon.

Thank you @FilipPyrek and @moelholm for helping out with this.

**Comment by bboure** [comment] 2020-07-29 20:32
Fixed in v0.7.0 🎉

**Comment by FilipPyrek** [comment] 2020-07-31 16:00
Unfortunately I'm not so sure about that @bboure 🙈 😞  https://github.com/aws-amplify/amplify-cli/issues/4439#issuecomment-667185144

**Comment by bboure** [comment] 2020-07-31 18:39
@FilipPyrek Thanks for your feedback. I just read your comment. I have seen that error a couple of times but I thought it was another unrelated issue. I now see how it is related. 😞 
Let's wait and see if we get a feedback. 

I will re-open this issue here.

Most of the time it has been working for me though.

**Comment by FilipPyrek** [comment] 2020-08-01 17:22
Also @bboure it seems to me, that with this update, there was introduced complete process exit when an error occurs in the amplify runtime provider. What about just logging the error and sending 500 response - but not killing the entire API. It's quite painful restarting it - especially when you use Webpack plugin...

**Comment by bboure** [comment] 2020-08-01 17:34
@FilipPyrek Thanks for the suggestion. Sounds good.
I will see how we can do that.

**Comment by bboure** [comment] 2020-08-17 09:10
Just opened a PR https://github.com/aws-amplify/amplify-cli/pull/5107
Hope this fixes it for good.

**Comment by FilipPyrek** [comment] 2020-10-06 18:57
Thanks @bboure. How is it looking? I can see that your PR has been merged. Was it also released yet?

**Comment by bboure** [comment] 2020-10-06 19:15
@FilipPyrek not yet. It was merged but I had to wait for them to actually release a new version. 
I think it is ok now. 
I will prepare a new version soon

**Comment by FilipPyrek** [comment] 2020-10-31 10:18
@bboure I can see that the Amplify fix has been released right now in CLI v4.32.0 🎉 
https://github.com/aws-amplify/amplify-cli/issues/4439#issuecomment-719847515

**Comment by bboure** [comment] 2020-10-31 10:21
@FilipPyrek Yes.
Although it was already released in a sub package previously. 
The fix should already be in v0.7.1

**Closed** 2020-12-17 15:00 UTC
